print("Basic mathematic operations in Python")
print()
print("Power :               5 ** 2 = ", 5 ** 2)
print("Multiplication :      5 * 2 =", 5 * 2)
print("Division :            5 / 2 =", 5 / 2)
print("Integere Division :   5 // 2 =", 5 // 2)
print("Remainder (modulo) :  5 % 2 =", 5 % 2)
print("Addition :            5 + 2 =", 5 + 2)
print("Subtraction :         5 - 2 =", 5 - 2)